_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  
  WEIGHTS: "/home/fariborz/detectron2/tools/deploy/model_final.pth"
  PIXEL_MEAN: [123.675, 116.28, 103.53]
  PIXEL_STD: [58.395, 57.12, 57.375]
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  BACKBONE:
    NAME: "build_swint_fpn_backbone"
  SWINT:
    OUT_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
  FPN:
    IN_FEATURES: ["stage2", "stage3", "stage4", "stage5"]

INPUT:
  FORMAT: "RGB"
SOLVER:
  STEPS: (8000000, 9000000)
  MAX_ITER: 10000000
  WEIGHT_DECAY: 0.05
  BASE_LR: 0.0001
  AMP:
    ENABLED: False 
TEST:
  EVAL_PERIOD: 20000 

DATASETS:
  TRAIN: ("experiment",)
  TEST: ("experiment_test",)
